apiVersion: v1
kind: Pod
metadata:
  name: webapp-pvc
spec:
  containers:
  - image:  kodekloud/event-simulator
    name: webapp
    env:
    - name: LOG_HANDLERS
      value: file
    volumeMounts:
    - mountPath: /log
      name: webapp-volume
  volumes:
  - name: webapp-volume
    hostPath:
      # directory location on host
      path: /var/log/webapp
      # this field is optional
      type: Directory