apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu
      command: 
          - "sleep"
          - "2000"
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]